### ISSUE TITLE
运行操作

### ISSUE THREAD

**Issue by dingjiayiyi** [thubim/ship-kg#1]
您好大佬，实在不好意思写出这么菜的问题。我用VS code运行，出现了Python版本很难处理的问题。这个Pyltp要用Python3.6，但是其他地方会出现问题。而用Python3.12的话跟资源包版本对不上。可以烦请大佬解答一下具体应该怎么解决或者这一套怎么操作下来呢？

**Comment by thubim** [comment]
项目的代码文件及README已经进行更新，您可以根据最新的README内容运行本项目。

**Comment by thubim** [comment]
> 您好大佬，实在不好意思写出这么菜的问题。我用VS code运行，出现了Python版本很难处理的问题。这个Pyltp要用Python3.6，但是其他地方会出现问题。而用Python3.12的话跟资源包版本对不上。可以烦请大佬解答一下具体应该怎么解决或者这一套怎么操作下来呢？

项目的代码文件及README已经进行更新，您可以根据最新的README内容运行本项目。

**Comment by dingjiayiyi** [comment]
谢谢谢谢！！！！！这些依赖都可以了，但是pyltp还是有问题。从python2.7试了好几个版本了，都没跑通。冒昧地问一下可以加您个联系方式嘛？我研究生也是这个方向，想跟您请教一下。

**Comment by thubim** [comment]
> 谢谢谢谢！！！！！这些依赖都可以了，但是pyltp还是有问题。从python2.7试了好几个版本了，都没跑通。冒昧地问一下可以加您个联系方式嘛？我研究生也是这个方向，想跟您请教一下。

我本地用python 3.8.8重新安装了一遍环境，pyltp是可以正常使用的。或者可以使用源码安装pyltp，https://github.com/HIT-SCIR/pyltp

**Comment by dingjiayiyi** [comment]
谢谢！！！！！！！！谢谢指导

**Comment by thubim** [comment]
> 谢谢谢谢！！！！！这些依赖都可以了，但是pyltp还是有问题。从python2.7试了好几个版本了，都没跑通。冒昧地问一下可以加您个联系方式嘛？我研究生也是这个方向，想跟您请教一下。

您可以添加我的微信：initxuan。
